### ISSUE TITLE
Support url-style image location references

### ISSUE THREAD

**Issue by brotchie** [tombenner/nui#57]
Instead of simply passing image paths as arguments to [`[UIImage imageNamed:]`](http://developer.apple.com/library/ios/#documentation/uikit/reference/UIImage_Class/Reference/Reference.html#//apple_ref/occ/clm/UIImage/imageNamed:), as in response to

``` css
Button {
    background-image: image.png;
}
```

Allow more explicit references to images at standard iOS file system locations, for example

``` css
Button {
    background-image: url(bundle://image.png);
    background-image-highlighted: url(caches://highlighted.png);
}
```

Bundle paths can be mapped directly to files using [`[NSBundle pathForResource:ofType:inDirectory:]`](https://developer.apple.com/library/mac/#documentation/Cocoa/Reference/Foundation/Classes/NSFileManager_Class/Reference/Reference.html#//apple_ref/occ/instm/NSFileManager/URLsForDirectory:inDomains:) while system specified directories can map prefixes to [`NSSearchPathDirectory`](https://developer.apple.com/library/mac/#documentation/Cocoa/Reference/Foundation/Miscellaneous/Foundation_Constants/Reference/reference.html#//apple_ref/doc/c_ref/NSSearchPathDirectory) enum items then mapped to files using [`[NSFileManager URLsForDirectory:inDomains:]`](https://developer.apple.com/library/mac/#documentation/Cocoa/Reference/Foundation/Classes/NSBundle_Class/Reference/Reference.html#//apple_ref/occ/instm/NSBundle/pathForResource:ofType:inDirectory:).

All these changes could be isolated to the [`[NUIConverter toImageFromImageName:]`](https://github.com/tombenner/nui/blob/master/NUI/Core/NUIConverter.m#L190) method. Retain existing behaviour if path is not wrapped in url().
